### ISSUE TITLE
tone categories

### ISSUE THREAD

**Issue by Wu-Urbanek** [lexibank/hsiuhmongmien#13]
In the raw data (https://github.com/lexibank/hsiuhmongmien/blob/master/raw/HM_official.tsv), there are some tones with /1, /2...etc. Are these the labels for tone categories?

**Comment by MuffinLinwist** [comment]
@LinguList, this has to do indeed with tone categories (also whether they are voiced or voiceless). is there a plan to do something with this (I'm asking in the context of the lexibank 2.0 release)? right now the cliff conversion does not include this.

**Comment by MuffinLinwist** [comment]
@LinguList brief reminder so we can have this issue resolved for the lexibank 2.0 release.

**Comment by LinguList** [comment]
@MuffinLinwist fixed now.
