### ISSUE TITLE
[SEALLABLE] problematic syllables

### ISSUE THREAD

**Issue by LinguList** [lexibank/hsiuhmongmien#14]
# Missing Values                         

|   Number | Segments     | Structure   |   Examples |
|---------:|:-------------|:------------|-----------:|
|        1 | p a i ⁵³     | i n ? t     |          6 |
|        2 | p ɑ i ³³     | i n ? t     |          2 |
|        3 | p a i ¹³     | i n ? t     |          2 |
|        4 | p e i ³³     | i n ? t     |          3 |
|        5 | p o i ⁴⁴     | i n ? t     |          2 |
|        6 | p u e ⁴⁴     | i n ? t     |          2 |
|        7 | ɬ a u ¹      | i n ? t     |          1 |
|        8 | ɬ a u ³³     | i n ? t     |          2 |
|        9 | tɕ e i ⁵³    | i n ? t     |          4 |
|       10 | ts e i ³³    | i n ? t     |          3 |
|       11 | ts ə i ¹     | i n ? t     |          1 |
|       12 | tsʰ a u ŋ ³³ | i ? n c t   |          1 |
|       13 | ɕ ɦ o ŋ ²²   | i ? n c t   |          1 |
|       14 | ɕ i o ŋ ⁶/¹³ | i ? n c t   |          1 |
|       15 | s ɦ o ŋ ¹²   | i ? n c t   |          1 |
|       16 | ɕ ɦ o ŋ ²³   | i ? n c t   |          1 |
|       17 | tɕ a u ⁵⁵    | i n ? t     |          1 |
|       18 | ʔ            | ?           |          4 |
|       19 | tɕ i u ⁸/³¹  | i n ? t     |          1 |
|       20 | tɕ e u ¹³    | i n ? t     |          1 |
|       21 | t i o ŋ ⁵³   | i ? n c t   |          1 |
|       22 | tɕ a i ³³    | i n ? t     |          3 |
|       23 | t ə i ³³     | i n ? t     |          2 |
|       24 | m j a u ³⁵   | i m n ? t   |          3 |
|       25 | k u ə ³³     | i n ? t     |          1 |
|       26 | t ə u ³⁵     | i n ? t     |          3 |
|       27 | tɕ e i ⁵⁵    | i n ? t     |          3 |
|       28 | l u ɔ ŋ ⁵³   | i ? n c t   |          1 |
|       29 | t a ɯ ³³     | i n ? t     |          3 |
|       30 | t o u ⁸/³¹   | i n ? t     |          1 |
|       31 | n e u ³⁵     | i n ? t     |          1 |
|       32 | t ɑ u ³⁵     | i n ? t     |          1 |
|       33 | t e u ¹³     | i n ? t     |          1 |
|       34 | t ɑ u ¹²     | i n ? t     |          1 |
|       35 | t ɤ u ⁵³     | i n ? t     |          1 |
|       36 | z ɯ ə ŋ ⁵³   | i ? n c t   |          1 |
|       37 | t ə u ⁵³     | i n ? t     |          2 |
|       38 | k u e ³⁵     | i n ? t     |          1 |
|       39 | t a i ⁵³     | i n ? t     |          3 |
|       40 | l j ə u ³²   | i m n ? t   |          1 |
|       41 | n ə u ³³     | i n ? t     |          2 |
|       42 | n o u ⁶/¹³   | i n ? t     |          1 |
|       43 | n e u ²²     | i n ? t     |          3 |
|       44 | n a i ¹²     | i n ? t     |          1 |
|       45 | n ɑ u ²³     | i n ? t     |          1 |
|       46 | n e u ⁵³     | i n ? t     |          1 |
|       47 | n ɤ u ⁴²     | i n ? t     |          1 |
|       48 | k u i ³⁵     | i n ? t     |          1 |
|       49 | s e i ²⁴     | i n ? t     |          1 |
|       50 | ɬ a u ŋ ³³   | i ? n c t   |          1 |
|       51 | l ə ɯ ⁵⁵     | i n ? t     |          1 |
|       52 | p a i ¹¹     | i n ? t     |          1 |
|       53 | ts ə i ³¹    | i n ? t     |          1 |
|       54 | l u i ³³     | i n ? t     |          2 |
|       55 | t ə u ³³     | i n ? t     |          2 |
|       56 | t a i ³³     | i n ? t     |          4 |
|       57 | p a u ³³     | i n ? t     |          1 |
|       58 | q a i ⁵³     | i n ? t     |          2 |
|       59 | q e i ³³     | i n ? t     |          2 |
|       60 | t a ɯ ⁵⁵     | i n ? t     |          1 |
|       61 | t a i ²²     | i n ? t     |          2 |
|       62 | t ɑ u ⁵⁵     | i n ? t     |          1 |
|       63 | t j ə u ⁵³   | i m n ? t   |          1 |
|       64 | kʰ a i ³³    | i n ? t     |          2 |
|       65 | t a ɯ ³⁵     | i n ? t     |          1 |
|       66 | n e i ³³     | i n ? t     |          1 |
|       67 | t a i ³⁵     | i n ? t     |          1 |
|       68 | q a i ³⁵     | i n ? t     |          1 |
|       69 | kʰ a i ⁵⁵    | i n ? t     |          1 |
|       70 | pʰ a i ³⁵    | i n ? t     |          1 |
|       71 | ʑ i u ⁵      | i n ? t     |          1 |
|       72 | s a u ⁵³     | i n ? t     |          1 |
|       73 | tɕ h u i ⁵³  | i ? n ? t   |          1 |
|       74 | ɬ a i ³³     | i n ? t     |          1 |
|       75 | k a u ⁵⁵     | i n ? t     |          1 |
|       76 | h ə u ³³     | i n ? t     |          1 |
|       77 | ʔ a u ³⁵     | i n ? t     |          1 |
|       78 | ȵ a i ⁵⁵     | i n ? t     |          2 |
|       79 | ŋ ɑ i ³⁵     | i n ? t     |          1 |
|       80 | n z e ⁵³     | i ? ? t     |          1 |
|       81 | ȵ a i ²      | i n ? t     |          1 |
|       82 | ȵ e i ³¹     | i n ? t     |          1 |
|       83 | n z e ²²     | i ? ? t     |          1 |
|       84 | n z ɑ ⁵⁵     | i ? ? t     |          1 |
|       85 | n j e i ²²   | i m n ? t   |          1 |
|       86 | m e i ⁵⁵     | i n ? t     |          1 |
|       87 | n ə u ⁵⁵     | i n ? t     |          3 |
|       88 | q e i ³⁵     | i n ? t     |          1 |
|       89 | k e i ⁴⁴     | i n ? t     |          2 |
|       90 | k e i ³⁵     | i n ? t     |          1 |
|       91 | ɣ ə u ⁵³     | i n ? t     |          1 |
|       92 | tɕ h i n ³⁵  | i ? n c t   |          2 |
|       93 | tɕ e u ³⁵    | i n ? t     |          1 |
|       94 | m̥            | ?           |          4 |
|       95 | ɑ i ⁴⁴       | ? n t       |          1 |
|       96 | ts ə i ³     | i n ? t     |          2 |
|       97 | m e i ⁴²     | i n ? t     |          1 |
|       98 | tɕ a i ⁵⁵    | i n ? t     |          2 |
|       99 | q u i ⁵⁵     | i n ? t     |          1 |
|      100 | qʰ a i ⁵³    | i n ? t     |          1 |
|      101 | l e i ⁵⁵     | i n ? t     |          1 |
|      102 | t ɦ ɒ ²¹     | i ? ? t     |          1 |
|      103 | t a u ⁴      | i n ? t     |          1 |
|      104 | t o u ¹²     | i n ? t     |          1 |
|      105 | t ɦ ɤ u ²²   | i ? n ? t   |          1 |
|      106 | t a u ¹²     | i n ? t     |          1 |
|      107 | ȵ a i ⁵³     | i n ? t     |          2 |
|      108 | ŋ ɑ i ³¹     | i n ? t     |          1 |
|      109 | n z e ²¹     | i ? ? t     |          2 |
|      110 | ȵ a i ⁴      | i n ? t     |          1 |
|      111 | ȵ e i ²⁴¹    | i n ? t     |          1 |
|      112 | n z ɑ ²²     | i ? ? t     |          1 |
|      113 | n j e i ²¹²  | i m n ? t   |          1 |
|      114 | ȵ e i ¹²     | i n ? t     |          1 |
|      115 | m e i ²¹     | i n ? t     |          1 |
|      116 | m e i ²⁴     | i n ? t     |          1 |
|      117 | l a i ³⁵     | i n ? t     |          1 |
|      118 | h a u ²⁴     | i n ? t     |          1 |
|      119 | x a u ³³     | i n ? t     |          1 |
|      120 | h a u ³³     | i n ? t     |          2 |
|      121 | tɕ ə i ⁵⁵    | i n ? t     |          1 |
|      122 | p e i ¹³     | i n ? t     |          5 |
|      123 | ɕ i ɑ ⁴⁴     | i n ? t     |          1 |
|      124 | ɣ a i ⁴⁴     | i n ? t     |          1 |
|      125 | ʑ e u ⁴⁴     | i n ? t     |          1 |
|      126 | ɣ u ɤ ³³     | i n ? t     |          1 |
|      127 | l i a ŋ ⁵⁵   | i ? n c t   |          1 |
|      128 | ȵ a u ⁵⁵     | i n ? t     |          1 |
|      129 | l j ə u ³³   | i m n ? t   |          1 |
|      130 | tɕ a i ³⁵    | i n ? t     |          1 |
|      131 | ȵ i u ⁵⁵     | i n ? t     |          1 |
|      132 | kʰ ɬ u ⁵³    | i ? ? t     |          1 |
|      133 | kʰ ɬ u ³³    | i ? ? t     |          1 |
|      134 | h ə u ⁵⁵     | i n ? t     |          3 |
|      135 | kʰ ə u ³⁵    | i n ? t     |          1 |
|      136 | tɕ e i ³³    | i n ? t     |          2 |
|      137 | ŋ o i ³³     | i n ? t     |          2 |
|      138 | t i u ⁸/³¹   | i n ? t     |          1 |
|      139 | ɬ j ɤ u ⁴⁴   | i m n ? t   |          1 |
|      140 | ɬ j a u ²²   | i m n ? t   |          1 |
|      141 | ȵ ʑ ɑ ŋ ³⁵   | i ? n c t   |          1 |
|      142 | ȵ i o ŋ ³    | i ? n c t   |          1 |
|      143 | ts ɑ i ³⁵    | i n ? t     |          1 |
|      144 | ts e i ²²    | i n ? t     |          1 |
|      145 | n ɑ u ³⁵⁴    | i n ? t     |          1 |
|      146 | l ə u ³⁵     | i n ? t     |          1 |
|      147 | l ɐ u ³³     | i n ? t     |          1 |
|      148 | ɬ e u ⁴⁴     | i n ? t     |          1 |
|      149 | ɬ ɑ u ⁴⁴     | i n ? t     |          1 |
|      150 | l ɑ u ²¹     | i n ? t     |          1 |
|      151 | l e u ⁴⁴     | i n ? t     |          1 |
|      152 | l e u ³³     | i n ? t     |          1 |
|      153 | l ɤ u ³³     | i n ? t     |          1 |
|      154 | g ə u ⁵³     | i n ? t     |          1 |
|      155 | ʔ d j ɔ ³⁵   | i ? ? ? t   |          1 |
|      156 | t j ə u ³⁵   | i m n ? t   |          1 |
|      157 | n a u ⁵³     | i n ? t     |          1 |
|      158 | t a u ³⁵     | i n ? t     |          1 |
|      159 | n e u ³¹     | i n ? t     |          1 |
|      160 | l a i ²²     | i n ? t     |          1 |
|      161 | n ɑ u ⁵⁵     | i n ? t     |          1 |
|      162 | n e u ⁵⁵     | i n ? t     |          1 |
|      163 | t e u ³³     | i n ? t     |          1 |
|      164 | n ɤ u ⁵⁵     | i n ? t     |          1 |
|      165 | p e i ²⁴     | i n ? t     |          1 |
|      166 | p a i ³³     | i n ? t     |          2 |
|      167 | sʰ e i ³³    | i n ? t     |          1 |
|      168 | h a u ⁵⁵     | i n ? t     |          1 |
|      169 | pʰ a i ⁵³    | i n ? t     |          1 |
|      170 | g ə u ³³     | i n ? t     |          1 |
|      171 | ŋ u i ⁵⁵     | i n ? t     |          1 |
|      172 | k ə u ³⁵     | i n ? t     |          1 |
|      173 | n ə i ⁵⁵     | i n ? t     |          1 |
|      174 | s e i ⁵⁵     | i n ? t     |          2 |
|      175 | tɕ ə u ³³    | i n ? t     |          1 |
|      176 | l a i ³³     | i n ? t     |          1 |
|      177 | l e i ³³     | i n ? t     |          3 |
|      178 | l ə i ³⁵     | i n ? t     |          2 |
|      179 | tʰ a u ³³    | i n ? t     |          2 |
|      180 | l e i ²⁴     | i n ? t     |          1 |
|      181 | l ə i ⁵      | i n ? t     |          1 |
|      182 | ɬ e i ⁴⁴     | i n ? t     |          1 |
|      183 | ʔ d a i ³⁵   | i ? n ? t   |          1 |
|      184 | tɕ a u ³⁵    | i n ? t     |          1 |
|      185 | l a u ³⁵     | i n ? t     |          2 |
|      186 | tɕ ə i ³³    | i n ? t     |          1 |
|      187 | p a i ³⁵     | i n ? t     |          2 |
|      188 | p ɑ i ³⁵     | i n ? t     |          1 |
|      189 | p a i ⁴⁴     | i n ? t     |          1 |
|      190 | p u e i ³⁵   | i ? n ? t   |          1 |
|      191 | p o i ³³     | i n ? t     |          1 |
|      192 | p u e ³³     | i n ? t     |          1 |
|      193 | ŋ e i ⁵³     | i n ? t     |          1 |
|      194 | g ə i ³⁵     | i n ? t     |          1 |
|      195 | g e i ³⁵     | i n ? t     |          1 |
|      196 | ɣ e i ⁴⁴     | i n ? t     |          1 |
|      197 | ʑ e i ⁴⁴     | i n ? t     |          1 |
|      198 | ɣ e i ³⁵     | i n ? t     |          1 |
|      199 | ŋ u i ³³     | i n ? t     |          1 |
|      200 | n z a ²²     | i ? ? t     |          1 |
|      201 | ȵ u ə ⁶/¹³   | i n ? t     |          1 |
|      202 | n z a u ¹²   | i ? n ? t   |          1 |
|      203 | n z u ²³     | i ? ? t     |          1 |
|      204 | ȶ a i ²²     | i n ? t     |          1 |
|      205 | ȶ ə u ⁵⁵     | i n ? t     |          1 |
|      206 | ʑ e u ²²     | i n ? t     |          1 |
|      207 | ɕ u ɤ ⁵⁵     | i n ? t     |          1 |
|      208 | q a u ³⁵     | i n ? t     |          1 |
|      209 | n a i ⁵⁵     | i n ? t     |          1 |
|      210 | ɣ ə u ³³     | i n ? t     |          1 |
|      211 | q ə i ⁵⁵     | i n ? t     |          1 |
|      212 | q a i ³³     | i n ? t     |          1 |
|      213 | t c o ŋ ⁵⁵   | i ? n c t   |          1 |
|      214 | ɬ a i ⁴⁴     | i n ? t     |          1 |
|      215 | l u i ⁵⁵     | i n ? t     |          1 |
|      216 | ɣ e i ³³     | i n ? t     |          2 |
|      217 | sʰ a i ³⁵    | i n ? t     |          1 |
|      218 | m a i ³⁵     | i n ? t     |          1 |
|      219 | h a i ⁵³     | i n ? t     |          1 |
|      220 | l e i ¹³     | i n ? t     |          2 |
|      221 | tɕ ə i ⁵³    | i n ? t     |          1 |
|      222 | kʰ ɬ ɔ ³³    | i ? ? t     |          1 |
|      223 | t a u ⁵³     | i n ? t     |          2 |
|      224 | th ə u ³³    | i n ? t     |          1 |
|      225 | n o u ³³     | i n ? t     |          1 |
|      226 | ɕ e u ²⁴     | i n ? t     |          1 |
|      227 | ɕʰ u ɤ ⁴⁴    | i n ? t     |          1 |
|      228 | t e i ⁴⁴     | i n ? t     |          1 |
|      229 | q e i ⁴⁴     | i n ? t     |          2 |
|      230 | g ə i ⁵³     | i n ? t     |          1 |
|      231 | ɣ e i ¹³     | i n ? t     |          1 |
|      232 | ʑ e i ²⁴     | i n ? t     |          1 |
|      233 | q ə u ²²     | i n ? t     |          1 |
|      234 | m u a ³³     | i n ? t     |          2 |
|      235 | n e i ²⁴     | i n ? t     |          1 |
|      236 | n e i ⁴⁴     | i n ? t     |          2 |
|      237 | t u i ⁵⁵     | i n ? t     |          1 |
|      238 | t õ i ³⁵⁴    | i n ? t     |          1 |
|      239 | t a u ³³     | i n ? t     |          2 |
|      240 | t u e ³³     | i n ? t     |          1 |
|      241 | t u a ¹³     | i n ? t     |          1 |
|      242 | t u ɛ ¹³     | i n ? t     |          1 |
|      243 | q u i ³⁵     | i n ? t     |          1 |
|      244 | t e i ²⁴     | i n ? t     |          1 |
|      245 | ȵ ʑ e ŋ ²¹   | i ? n c t   |          1 |
|      246 | n ɑ u ³³     | i n ? t     |          1 |
|      247 | p ə u ³⁵     | i n ? t     |          1 |
|      248 | t ɑ i ²⁴     | i n ? t     |          1 |
|      249 | h a u ¹      | i n ? t     |          1 |
|      250 | h o u ²⁴     | i n ? t     |          1 |
|      251 | h ɑ u ³³     | i n ? t     |          1 |
|      252 | h e ɯ ⁴⁴     | i n ? t     |          1 |
|      253 | h ɤ u ⁴⁴     | i n ? t     |          1 |
|      254 | m ɑ ŋ̃        | i n ?       |          1 |
|      255 | ⁴⁵³          | ?           |          1 |
|      256 | e i ³³       | ? n t       |          1 |
|      257 | m e i ⁴⁴     | i n ? t     |          1 |
|      258 | sʰ o u ³³    | i n ? t     |          1 |
|      259 | s e ɯ ³³     | i n ? t     |          1 |
|      260 | sʰ o u ¹¹    | i n ? t     |          1 |
|      261 | n a i ³³     | i n ? t     |          1 |
|      262 | s a i ⁵⁵     | i n ? t     |          1 |
|      263 | ɬ o u ²⁴     | i n ? t     |          1 |
|      264 | ɬ ɤ u ³³     | i n ? t     |          1 |
|      265 | k u ɑ n ³⁵   | i ? n c t   |          1 |
|      266 | k u æ̃ ¹³     | i n ? t     |          1 |
|      267 | v a i ³³     | i n ? t     |          1 |
|      268 | t ə i ³⁵     | i n ? t     |          1 |
|      269 | q ə u ³¹     | i n ? t     |          1 |
|      270 | k u ɑ n ⁵³   | i ? n c t   |          1 |
|      271 | f a u ⁴²     | i n ? t     |          1 |
|      272 | k u æ̃ ⁵⁵     | i n ? t     |          1 |
|      273 | t ə i ⁵⁵     | i n ? t     |          1 |

# Syllable Errors

|   Number | Segments            | Structure         |   Examples |
|---------:|:--------------------|:------------------|-----------:|
|        1 | p u a ¹³ t e u ⁵³   | � � � � � � � �   |          1 |
|        2 | t ɑ ²¹ q ɛ ³³       | � � � � � �       |          1 |
|        3 | n u ³² tɕ e i ⁵⁵    | � � � � � � �     |          1 |
|        4 | p e i ¹³ m e ⁵⁵     | � � � � � � �     |          1 |
|        5 | ts ẽ i ⁴⁵³ m ɑ ²²   | � � � � � � �     |          1 |
|        6 | n̥ j u ¹³ m o ²²     | � � � � � � �     |          1 |
|        7 | p e i ¹³ m e ²²     | � � � � � � �     |          1 |
|        8 | ɕ i n ²⁴ t e u ²²   | � � � � � � � �   |          1 |
|        9 | t ɑ ²¹ l e ²⁴       | � � � � � �       |          1 |
|       10 | t j e u ¹³ l a ¹³   | � � � � � � � �   |          1 |
|       11 | ʔ d j o ŋ ³³        | � � � � � �       |          1 |
|       12 | t j u ŋ ²⁴ n j y ⁵³ | � � � � � � � � � |          1 |
|       13 | q e i ²⁴ q e i ²⁴   | � � � � � � � �   |          1 |
|       14 | p ɔ ¹³ ɣ i ⁴⁴       | � � � � � �       |          1 |

**Comment by MuffinLinwist** [comment]
This is fixed.
